- hosts: redmine-servers

  roles:
    - system
    - ruby
    - redmine
    - apache

  post_tasks:
    - name: 完了
      debug:
        msg='インストールが完了しました。 http://{{ guest_id }}/redmine/ にアクセスしてください。'
